# Generated by Django 5.0.3 on 2024-03-14 19:15

import myapp.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Организация', 'verbose_name_plural': 'Организации'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', myapp.managers.UserManager()),
            ],
        ),
    ]
